const { chromium } = require(process.env.BINGO_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http');
const { pathToFileURL }=require('node:url');
const B=require('../js/domain.js');
const out=path.join(__dirname,'artifacts/folder');fs.mkdirSync(out,{recursive:true});
function wav(){const n=24000,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(3000*Math.sin(i/8000*880*Math.PI*2)),44+i*2);return b;}
const folder=fs.mkdtempSync(path.join(out,'Musica-')),empty=fs.mkdtempSync(path.join(out,'Sin-audios-'));
for(const name of ['A/tema.wav','B/tema.wav','Don.wav']){const target=path.join(folder,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,wav());}
fs.writeFileSync(path.join(folder,'foto.png'),'image');fs.writeFileSync(path.join(folder,'vacío.mp3'),'');fs.writeFileSync(path.join(empty,'nota.txt'),'sin audios');
const ready=p=>p.waitForFunction(()=>document.getElementById('lock-warning').hidden),state=p=>p.evaluate(()=>BingoStorage.read());
const row=(p,n)=>p.locator('.folder-song').nth(n), title=(p,n)=>row(p,n).locator('input:not([type=checkbox])');
async function prepare(p){await p.locator('[data-view="sets"]').click();await p.locator('#set-mode').selectOption('music');await p.locator('#songs-folder').setInputFiles(folder);}
async function generate(p){await p.locator('#music-card-size').fill('1');await p.locator('#set-name').fill('Carpeta QA');await p.locator('#quantity').fill('2');await p.locator('#generate').click();await p.waitForFunction(()=>document.querySelectorAll('.set-row').length===1);await p.waitForFunction(()=>!document.getElementById('generate').disabled);}
let browser,server;
(async()=>{
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[],requests=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()!=='GET'||/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8080'))requests.push(r.url());});
 await p.goto('http://127.0.0.1:8080');await ready(p);
 await p.evaluate(()=>{window.loads=0;window.reads=0;const load=HTMLMediaElement.prototype.load;HTMLMediaElement.prototype.load=function(){if(this.preload==='metadata')window.loads++;return load.call(this);};const read=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){window.reads++;return read.call(this);};});
 await prepare(p);assert.equal(await p.locator('.folder-song').count(),3);assert.equal(await title(p,0).inputValue(),'tema');assert.equal(await title(p,1).inputValue(),'tema');
 assert.equal(await p.locator('#songs-file,#songs-format,#songs-separator,#draft-files,#draft-reference-1').count(),0);assert.match(await p.locator('#songs-summary').innerText(),/2 archivos ignorados/);assert.equal(await p.evaluate(()=>window.loads+window.reads),0);
 await title(p,1).fill('Mi canción');const secondPath=await row(p,1).locator('.reference-status').innerText();await row(p,1).locator('[data-move="-1"]').click();assert.equal(await title(p,0).inputValue(),'Mi canción');assert.equal(await row(p,0).locator('.reference-status').innerText(),secondPath);assert(await row(p,0).locator('input[type=checkbox]').evaluate(e=>e===document.activeElement));
 await row(p,2).locator('input[type=checkbox]').uncheck();assert.match(await row(p,2).locator('.folder-number').innerText(),/excluida/);assert.equal(await p.locator('#quantity').getAttribute('max'),'1');
 await title(p,0).fill('');assert(await p.locator('#generate').isDisabled());await title(p,0).fill('Mi canción');
 await p.locator('#songs-folder').evaluate(e=>e.dispatchEvent(new Event('cancel')));assert.equal(await title(p,0).inputValue(),'Mi canción');
 await p.locator('#songs-folder').setInputFiles(empty);assert.equal(await title(p,0).inputValue(),'Mi canción');assert.match(await p.locator('#notice').innerText(),/no contiene audios/);
 for(const mode of ['light','dark'])for(const palette of ['forest','ocean','plum']){await p.evaluate(v=>BingoAppearance.set(v),{mode,palette});await p.screenshot({path:path.join(out,`${mode}-${palette}.png`),fullPage:true});}
 await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#folder-review').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'mobile.png')});await row(p,1).locator('[data-move="-1"]').scrollIntoViewIfNeeded();assert(await row(p,1).locator('[data-move="-1"]').isVisible());await p.setViewportSize({width:1440,height:1000});
 await p.locator('#music-card-size').fill('1');
 await p.evaluate(()=>{window.realUpdate=BingoStorage.update;BingoStorage.update=async()=>{throw Error('Fallo de guardado de prueba');};});await p.locator('#set-name').fill('Carpeta QA');await p.locator('#quantity').fill('2');await p.locator('#generate').click();await p.waitForFunction(()=>!document.getElementById('generate').disabled);assert.equal((await state(p)).sets.length,0);assert.equal((await state(p)).nextCode,1);assert.equal(await title(p,0).inputValue(),'Mi canción');
 await p.evaluate(()=>{BingoStorage.update=async fn=>{await new Promise(r=>window.finishWrite=r);return window.realUpdate(fn);};});await p.locator('#generate').click();await p.waitForFunction(()=>!!window.finishWrite);assert(await p.locator('#songs-folder').isDisabled());assert(await title(p,0).isDisabled());assert(await row(p,0).locator('[data-move="1"]').isDisabled());await p.evaluate(()=>{BingoStorage.update=window.realUpdate;window.finishWrite();});await p.waitForFunction(()=>document.querySelectorAll('.set-row').length===1&&!document.getElementById('generate').disabled);
 const saved=await state(p),set=saved.sets[0];assert.deepEqual(set.songs,['Mi canción','tema']);assert.equal(set.audioRefs[0],secondPath);assert.equal(set.cards.length,2);assert(set.cards.every(c=>c.numbers.every(n=>n<=2)));
 await p.getByRole('button',{name:'♫ Audios',exact:true}).click();assert.match(await p.locator('#reference-status-1').innerText(),/B\/tema.wav/);assert.match(await p.locator('#reference-status-2').innerText(),/A\/tema.wav/);
 await p.locator('#clip-start-1').fill('00:01');await p.locator('#clip-end-1').fill('00:02');await p.locator('#clip-row-1 [data-clip-action=save]').click();await p.waitForFunction(()=>document.getElementById('clip-saved-1').textContent.includes('00:01 → 00:02'));await p.keyboard.press('Escape');
 await p.getByRole('button',{name:'Ver / Imprimir',exact:true}).click();assert(!(await p.locator('#print-root').innerText()).includes('Don'));assert(!(await p.locator('#print-root').innerText()).includes('.wav'));await p.keyboard.press('Escape');
 await p.getByRole('button',{name:'Jugar →',exact:true}).click();await p.locator('#game-form button[type=submit]').click();await p.waitForFunction(()=>!document.getElementById('game-dialog').open);assert.equal(await p.locator('.number-cell').count(),2);await p.evaluate(()=>Bingo.draw=()=>1);await p.locator('#draw').click();await p.waitForFunction(()=>!document.getElementById('music-player').paused&&document.getElementById('music-player').currentTime>=1);await p.waitForFunction(()=>document.getElementById('music-player').paused);assert.deepEqual((await state(p)).games[0].drawn,[1]);
 const beforeReload=await state(p);await p.reload();await ready(p);await p.locator('[data-view="sets"]').click();await p.getByRole('button',{name:'♫ Audios',exact:true}).click();assert.equal(await p.locator('#audio-link-1').inputValue(),'');await p.locator('#audio-folder').setInputFiles(folder);assert.match(await p.locator('#reference-status-1').innerText(),/B\/tema.wav/);assert.deepEqual(await state(p),beforeReload);await p.keyboard.press('Escape');
 const download=p.waitForEvent('download');await p.locator('#export').click();const backup=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));assert.deepEqual(backup,beforeReload);
 const bad=structuredClone(backup);bad.sets[0].audioRefs=['http://bad'];await p.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForFunction(()=>document.getElementById('notice').textContent.includes('No se pudo restaurar'));assert.deepEqual(await state(p),beforeReload);
 await p.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.locator('#confirm-import').click();await p.waitForFunction(()=>!document.getElementById('confirm-dialog').open);await p.getByRole('button',{name:'♫ Audios',exact:true}).click();assert.equal(await p.locator('#audio-link-1').inputValue(),'');await p.keyboard.press('Escape');
 // La nueva selección reemplaza, el cambio de modalidad descarta.
 await p.locator('#set-mode').selectOption('music');await p.locator('#songs-folder').setInputFiles(folder);await title(p,0).fill('Borrador');await p.locator('#songs-folder').setInputFiles(folder);assert.equal(await title(p,0).inputValue(),'tema');await p.locator('#set-mode').selectOption('classic');await p.locator('#set-mode').selectOption('music');assert.equal(await p.locator('.folder-song').count(),0);assert(await p.locator('#generate').isDisabled());
 const thirty=fs.mkdtempSync(path.join(out,'Treinta-'));for(let i=1;i<=31;i++)fs.writeFileSync(path.join(thirty,`${i}.mp3`),'audio');await p.locator('#songs-folder').setInputFiles(thirty);await row(p,30).locator('input[type=checkbox]').uncheck();assert.match(await p.locator('#songs-summary').innerText(),/30 canciones incluidas/);assert.match(await p.locator('#quantity-help').innerText(),/15 canciones/);
 const readonly=await context.newPage();await readonly.goto('http://127.0.0.1:8080');await readonly.waitForTimeout(200);assert(await readonly.locator('#songs-folder').isDisabled());await readonly.close();
 const unsupported=await browser.newPage();await unsupported.addInitScript(()=>delete HTMLInputElement.prototype.webkitdirectory);await unsupported.goto('http://127.0.0.1:8080');await ready(unsupported);await unsupported.locator('[data-view="sets"]').click();await unsupported.locator('#set-mode').selectOption('music');assert(await unsupported.locator('#songs-folder').isDisabled());assert(await unsupported.locator('#folder-support').isVisible());await unsupported.close();
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 server=http.createServer((req,res)=>{const relative=new URL(req.url,'http://localhost').pathname.replace(/^\/bingo\//,'');const file=path.join(__dirname,'..',relative);if(!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 for(const url of [pathToFileURL(path.resolve('index.html')).href,`http://127.0.0.1:${server.address().port}/bingo/index.html`]){const q=await browser.newPage();await q.goto(url);await ready(q);await prepare(q);await generate(q);assert.equal((await state(q)).sets[0].songs.length,3);await q.close();}
 console.log('PASS carpeta: revisión, orden, exclusiones, archivos correctos, cancelación, fallos, bloqueo, audio y clips, recarga, respaldo, impresión, móvil, temas, permisos, privacidad, file y subdirectorio.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
